### ISSUE TITLE
Not able to see http2 bzm sampler in jmeter 5.6.2

### ISSUE THREAD

**Issue by heysarthak** [Blazemeter/jmeter-http2-plugin#60]
Hi team i installed the plugin in jmeter 5.6.2 but i am not able to sampler in the GUI

**Comment by heysarthak** [comment]
![image](https://github.com/Blazemeter/jmeter-http2-plugin/assets/74072442/7508cd7e-18a6-474d-889e-13853f60d127)
![image](https://github.com/Blazemeter/jmeter-http2-plugin/assets/74072442/dd8b5100-8747-4354-9963-1600a22244f4)

**Comment by AddRemover** [comment]
same issue here

**Comment by Baraujo25** [comment]
Hi, thanks for reporting the issue!

Since JMeter 5.6.x there were a few changes in the HTTP Panel which we consume in order to re-utilize the UI component and create the HTTP2 Sampler panel.

HTTP2 sampler is not displayed since an exception is thrown due to the above-mentioned changes done by the JMeter team.

In the meantime, I'll highly recommend you use JMeter version 5.5.x or lower.

We are currently working on the issue.

Expect a release with the corresponding fix.

Again, thanks for reporting.

Bests,

**Comment by heysarthak** [comment]
Hi Joaquin,

By when can we expect the fix, do we have any timeline?

Thanks 
Sarthak

**Comment by 3dgiordano** [comment]
Hi @heysarthak 

The fix was released in version 2.0.4.
You can download it from the version in the Releases section or you can wait for it to be available in Plugin Manager.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.4

Let me know if the version works correctly for you in order to close the issue.
Thank you

**Comment by heysarthak** [comment]
Jmeter Version 5.6.1 http2 2.0.2

Creating summariser <summary>
Created the tree successfully using /var/lib/jenkins/ocslf_tests/data/traffic/jsons/config_without_ramping.jmx
Starting standalone test @ 2023 Oct 6 13:37:43 UTC (1696599463801)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +   1159 in 00:00:16 =   72.2/s Avg:    22 Min:    15 Max:   126 Err:     0 (0.00%) Active: 3 Started: 1161 Finished: 1158
summary +  21506 in 00:00:30 =  717.0/s Avg:     7 Min:     2 Max:    44 Err:     0 (0.00%) Active: 175 Started: 2225 Finished: 2050
summary =  22665 in 00:00:46 =  492.3/s Avg:     8 Min:     2 Max:   126 Err:     0 (0.00%)

Jmeter Version 5.6.2 http2 2.0.4

Creating summariser <summary>
Created the tree successfully using /var/lib/jenkins/ocslf_tests/data/traffic/jsons/config_without_ramping.jmx
Starting standalone test @ 2023 Oct 6 13:33:41 UTC (1696599221904)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +   1352 in 00:00:18 =   75.4/s Avg:     2 Min:     1 Max:   126 Err:  1352 (100.00%) Active: 1 Started: 1352 Finished: 1351

**Comment by heysarthak** [comment]
Hi team i think its sending http1.1 in v2.0.4 , as my request only contaions http2 requests.

**Comment by heysarthak** [comment]
Hi Team, 

I just want to know, what options do i have now, as the latest apache and http2 plugin versions are not working with each other, and http2 v2.0.2 contains jetty version in 11.0.10 which has a lot of CVEs. 

Thanks 
Sarthak

**Comment by 3dgiordano** [comment]
Hi @heysarthak 

Any issue or question not related to the incident reported in the original card must be entered in its own issue on GitHub.

We appreciate not incorporating topics not related in order to maintain focus on the main topic that was originally reported.

Thank you

**Comment by 3dgiordano** [comment]
Hi @heysarthak 

The original issue is related to the sample not appearing for use in JMeter 5.6.x
That issue was resolved in release 2.0.4.
If the issue was solved in that version, I would appreciate your confirmation, that way I will proceed to close the issue.

Any other doubt or question or report, not related to the original issue, you can create a new issue on GitHub.
It is in order to allow each of them their correct management.

I await confirmation that it is now available for use in JMeter 5.6.x.

Thank you.

**Comment by heysarthak** [comment]
yeah it has started appearing.

**Comment by AddRemover** [comment]
as I already reported, original issue seems to be solved, however, plugin does not sent HTTP2.0 messages as supposed to do. Instead, all outgoing messages are HTTP1.1
Should be reported as new issue?

**Comment by 3dgiordano** [comment]
Hi @AddRemover 

Yes, create a new issue with your evidence that demonstrates the problem, or with the doubt.

Thanks.

**Comment by 3dgiordano** [comment]
I close this issue related to the fact that it was not possible to use the HTTP2 plugin in JMeter 5.6.x.
Any other issue or a new issue related to any other problem related to JMeter 5.6.x must be created a new issue.
